Revert "NIFI-9392 PutHive3Streaming processor throws java.lang.NoClassDefFoundError on startup"
This commit on 1.16 isn't quite ready so removing from the 1.15.1 release

This reverts commit 8581799f78dadfe81bac1b6a66438e51c017e6d6.