NIFI-9552 Fix NoClassDefFound error in case of nifi-registry-ranger-assembly
Without define the jcl-over-slf4j runtime dependency, the assembly plugin will not copy the jcl jar to the ranger lib directory,
which cause NoClassDefFoundError in some cases

This closes #5663

Signed-off-by: David Handermann <exceptionfactory@apache.org>