NIFI-13775 Fixed NoClassDefFoundError with ArrayUtils in ConsumeKafka (#9287)
- Upgraded Kafka Clients from 3.7.1 to 3.8.0
- Inheriting from the correct base services-api instead of shared-bundle then identifying missing explicit dependencies of Kafka processors commons-lang3 and commons-codec

Signed-off-by: David Handermann <exceptionfactory@apache.org>