NIFI-9552 Fix the same NoClassDefFound error in case of nifi-registry ranger plugin Without define the jcl runtime dependency, the assembly plugin will not copy the jcl jar to the ranger lib directory, which cause NoClassDefFoundError in some cases